{% set name = "just" %}
{% set version = "1.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/casey/just/archive/{{ version }}.tar.gz
  sha256: 3d47e27755d39f40e1ca34bc0ef535fa514e7ed547b2af62311dcadd8bd6d564

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - just --help

about:
  home: https://github.com/casey/just
  license: CC0-1.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: just is a handy way to save and run project-specific commands.

extra:
  recipe-maintainers:
    - kellpossible
    - dbast
