{% set name = "just" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/casey/just/archive/{{ version }}.tar.gz
  sha256: f2359040c02392bcc11c9a1ca13fef8089e509cb64eb342e20c96f9edd5c1e55

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - just --help

about:
  home: https://github.com/casey/just
  license: CC0-1.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: just is a handy way to save and run project-specific commands.

extra:
  recipe-maintainers:
    - kellpossible
    - dbast
